//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvery.Surveryer.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smsSurvery.Surveryer.GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords &apos;{0}&apos; detected.
        /// </summary>
        public static string alertCauseAllKeywordsDetectedMessage {
            get {
                return ResourceManager.GetString("alertCauseAllKeywordsDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword &apos;{0}&apos; detected.
        /// </summary>
        public static string alertCauseAnyKeywordDetectedMessage {
            get {
                return ResourceManager.GetString("alertCauseAnyKeywordDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword &apos;{0}&apos; detected.
        /// </summary>
        public static string alertCauseContainsMessage {
            get {
                return ResourceManager.GetString("alertCauseContainsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected answer, &apos;{0}&apos;, received.
        /// </summary>
        public static string alertCauseEqualMessage {
            get {
                return ResourceManager.GetString("alertCauseEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received answer &apos;{0}&apos; ({1}) &gt; than threshold answer &apos;{2}&apos; ({3}).
        /// </summary>
        public static string alertCauseGreaterMessage {
            get {
                return ResourceManager.GetString("alertCauseGreaterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received answer &apos;{0}&apos; ({1}) &gt;= than threshold answer &apos;{2}&apos; ({3}).
        /// </summary>
        public static string alertCauseGreaterOrEqualMessage {
            get {
                return ResourceManager.GetString("alertCauseGreaterOrEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received answer &apos;{0}&apos; ({1}) &lt; than threshold answer &apos;{2}&apos; ({3}).
        /// </summary>
        public static string alertCauseLessMessage {
            get {
                return ResourceManager.GetString("alertCauseLessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received answer &apos;{0}&apos; ({1}) &lt;= than threshold answer &apos;{2}&apos; ({3}).
        /// </summary>
        public static string alertCauseLessOrEqualMessage {
            get {
                return ResourceManager.GetString("alertCauseLessOrEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer different from expected value &apos;{0}&apos;.
        /// </summary>
        public static string alertCauseNotEqualMessage {
            get {
                return ResourceManager.GetString("alertCauseNotEqualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; not detected.
        /// </summary>
        public static string alertCauseNotSelectedOption {
            get {
                return ResourceManager.GetString("alertCauseNotSelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; detected.
        /// </summary>
        public static string alertCauseSelectedOption {
            get {
                return ResourceManager.GetString("alertCauseSelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert &apos;{0}&apos; triggered for question &apos;{1}&apos;.
        /// </summary>
        public static string alertEmailSubject {
            get {
                return ResourceManager.GetString("alertEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. john@smith.com.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mandatory.
        /// </summary>
        public static string MandatoryQuestion {
            get {
                return ResourceManager.GetString("MandatoryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string MobileSurveyFooterCaption {
            get {
                return ResourceManager.GetString("MobileSurveyFooterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like to be informed about the steps taken by us to improve on your feedback please leave us some personal details:.
        /// </summary>
        public static string MobileSurveyLeavePersonalInfoLabel {
            get {
                return ResourceManager.GetString("MobileSurveyLeavePersonalInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MobileSurveyNoLabel {
            get {
                return ResourceManager.GetString("MobileSurveyNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Survey.
        /// </summary>
        public static string MobileSurveyPageTitle {
            get {
                return ResourceManager.GetString("MobileSurveyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string MobileSurveyPersonalInfoEmailError {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MobileSurveyPersonalInfoEmailLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name cannot be empty or whitespace only.
        /// </summary>
        public static string MobileSurveyPersonalInfoNameError {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MobileSurveyPersonalInfoNameLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string MobileSurveyPersonalInfoPhoneLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake survey.
        /// </summary>
        public static string MobileSurveyPersonalInfoRetakeSurvey {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoRetakeSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit personal info.
        /// </summary>
        public static string MobileSurveyPersonalInfoSubmitBtnLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoSubmitBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information submitted. Thank you!.
        /// </summary>
        public static string MobileSurveyPersonalInfoSubmittedLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoSubmittedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Surname cannot be empty or whitespace only.
        /// </summary>
        public static string MobileSurveyPersonalInfoSurnameError {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoSurnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string MobileSurveyPersonalInfoSurnameLabel {
            get {
                return ResourceManager.GetString("MobileSurveyPersonalInfoSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify your answer and help us improve.
        /// </summary>
        public static string MobileSurveyRatingAddionalInfoLabel {
            get {
                return ResourceManager.GetString("MobileSurveyRatingAddionalInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an answer.
        /// </summary>
        public static string MobileSurveySelectOneFromManyLabel {
            get {
                return ResourceManager.GetString("MobileSurveySelectOneFromManyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string MobileSurveySubmitButtonCaption {
            get {
                return ResourceManager.GetString("MobileSurveySubmitButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This survey has already been been submitted. Thank you!.
        /// </summary>
        public static string MobileSurveySubmittedMessage {
            get {
                return ResourceManager.GetString("MobileSurveySubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey already submitted.
        /// </summary>
        public static string MobileSurveySubmittedPageTitle {
            get {
                return ResourceManager.GetString("MobileSurveySubmittedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey completed.
        /// </summary>
        public static string MobileSurveySubmittedTitle {
            get {
                return ResourceManager.GetString("MobileSurveySubmittedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey sent.
        /// </summary>
        public static string MobileSurveySurveySent {
            get {
                return ResourceManager.GetString("MobileSurveySurveySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MobileSurveyYesLabel {
            get {
                return ResourceManager.GetString("MobileSurveyYesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. John/Jane.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activity detected, are you still there?.
        /// </summary>
        public static string NoActivityDetected {
            get {
                return ResourceManager.GetString("NoActivityDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 01332 050999.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionLabel {
            get {
                return ResourceManager.GetString("RegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the survey at {0}.
        /// </summary>
        public static string SmsMobileSurveyTemplate {
            get {
                return ResourceManager.GetString("SmsMobileSurveyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reply.
        /// </summary>
        public static string SmsQuestionFreeTextSuffix {
            get {
                return ResourceManager.GetString("SmsQuestionFreeTextSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q{0}/{1}: .
        /// </summary>
        public static string SmsQuestionIndexTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionIndexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        public static string SmsQuestionNumericSuffixJoinTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionNumericSuffixJoinTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with:.
        /// </summary>
        public static string SmsQuestionNumericSuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionNumericSuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} out of {2} stars.
        /// </summary>
        public static string SmsQuestionRatingSuffixJoinTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionRatingSuffixJoinTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with:.
        /// </summary>
        public static string SmsQuestionRatingSuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionRatingSuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        public static string SmsQuestionSelectManyFromManyMemberSuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionSelectManyFromManyMemberSuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply by responding with the selected options, separated by comma (e.g. 1,2,4):.
        /// </summary>
        public static string SmsQuestionSelectManyFromManySuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionSelectManyFromManySuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        public static string SmsQuestionSelectOneFromManyMemberSuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionSelectOneFromManyMemberSuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with:.
        /// </summary>
        public static string SmsQuestionSelectOneFromManySuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionSelectOneFromManySuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with:
        ///1 for Yes
        ///2 for No.
        /// </summary>
        public static string SmsQuestionYesNoSuffixTemplate {
            get {
                return ResourceManager.GetString("SmsQuestionYesNoSuffixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Smith.
        /// </summary>
        public static string SurnamePlaceholder {
            get {
                return ResourceManager.GetString("SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer is....
        /// </summary>
        public static string TextareaPlaceholder {
            get {
                return ResourceManager.GetString("TextareaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I am here!.
        /// </summary>
        public static string YesIAmHere {
            get {
                return ResourceManager.GetString("YesIAmHere", resourceCulture);
            }
        }
    }
}
