//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertNotificationSet
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string DistributionList { get; set; }
        public int QuestionAlertId { get; set; }
    
        public virtual QuestionAlertSet QuestionAlertSet { get; set; }
    }
}
