//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SurveyResult = new HashSet<SurveyResult>();
        }
    
        public string PhoneNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<SurveyResult> SurveyResult { get; set; }
    }
}
