//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAlertSet
    {
        public QuestionAlertSet()
        {
            this.AlertNotificationSet = new HashSet<AlertNotificationSet>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Operator { get; set; }
        public string TriggerAnswer { get; set; }
        public int QuestionId { get; set; }
        public string Tags_CompanyName { get; set; }
        public Nullable<int> Tags_Id { get; set; }
    
        public virtual ICollection<AlertNotificationSet> AlertNotificationSet { get; set; }
        public virtual Question QuestionSet { get; set; }
        public virtual Tags LocationTag { get; set; }
    }
}
