//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Result = new HashSet<Result>();
            this.SurveyResultSet = new HashSet<SurveyResult>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int Order { get; set; }
        public string Type { get; set; }
        public string ValidAnswers { get; set; }
        public string ValidAnswersDetails { get; set; }
        public int SurveyPlan_Id { get; set; }
    
        public virtual ICollection<Result> Result { get; set; }
        public virtual SurveyPlan SurveyPlanSet { get; set; }
        public virtual ICollection<SurveyResult> SurveyResultSet { get; set; }
    }
}
