//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.SurveyPlan = new HashSet<SurveyPlan>();
            this.Result = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int Order { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<SurveyPlan> SurveyPlan { get; set; }
        public virtual ICollection<Result> Result { get; set; }
    }
}
