//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsSurvey.dbInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyPlan
    {
        public SurveyPlan()
        {
            this.Questions = new HashSet<Question>();
            this.SurveyResult = new HashSet<SurveyResult>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string ThankYouMessage { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<SurveyResult> SurveyResult { get; set; }
    }
}
